[package]
name = "rt1010-rs-blinky"
version = "0.1.0"
edition = "2021"

[dependencies]
imxrt-ral = { version = "*", features = ["imxrt1011", "rt"] }
cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
panic-halt = "1.0.0"

[dependencies.cortex-m-rt]
features = ["device"]
version = "0.7"

[[bin]]
name = "rt1010-rs-blinky"
test = false
bench = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
