[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
rustflags = [
    "-C", "link-arg=-Timxrt-link.x",
    "-C", "link-arg=-error-limit=0",
    "-C", "link-arg=-nmagic",
]
runner = "probe-rs run --chip=mimxrt1010"
